# Generated by Django 5.1.1 on 2024-09-29 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloProyecto', models.CharField(default='No tiene nombre', max_length=100)),
                ('precio', models.BigIntegerField(default=0)),
                ('ubicacion', models.CharField(default='No se especifica la ubicacion', max_length=100)),
                ('descripcion', models.CharField(default='No tiene una descripcion', max_length=100)),
                ('proyectoImagenPrincipal', models.ImageField(default='No tiene imagenes', upload_to='static/proyectoImages/')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenesProyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenProyecto', models.ImageField(upload_to='static/proyectoImages/')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyectos.proyect')),
            ],
        ),
        migrations.CreateModel(
            name='VideoProyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoProyecto', models.FileField(upload_to='static/videosProyectos/')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyectos.proyect')),
            ],
        ),
    ]
