# Generated by Django 5.1.1 on 2024-09-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyect',
            name='descripcion',
            field=models.TextField(default='No tiene una descripcion', max_length=100),
        ),
    ]
