# Generated by Django 5.1.1 on 2024-09-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacionInmobiliaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha', models.DateField(default='2005/08/09')),
                ('precio', models.IntegerField(default=0)),
                ('descripcion', models.TextField(default=0)),
                ('imagenes', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
