# Generated by Django 5.1.2 on 2024-10-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registo_Inicio', '0004_alter_imagenpublicacion_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacioninmobiliaria',
            name='numeroBaños',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publicacioninmobiliaria',
            name='numeroCamas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publicacioninmobiliaria',
            name='numeroDormitorios',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publicacioninmobiliaria',
            name='tamaño',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publicacioninmobiliaria',
            name='tipoInmueble',
            field=models.CharField(choices=[('Casa', 'Casa'), ('Apartamento', 'Apartamento')], default='Casa', max_length=50),
        ),
    ]
