# Generated by Django 5.1.2 on 2024-11-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registo_Inicio', '0005_publicacioninmobiliaria_numerobaños_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacioninmobiliaria',
            name='ciudad',
            field=models.CharField(default='No tiene', max_length=30),
        ),
    ]
